/**
 * Linux ISOs Search Provider
 * Curated list of popular Linux distributions with official torrent/magnet links.
 */

const LINUX_ISOS = [
  {
    id: 'ubuntu-24.04.2-desktop',
    name: 'Ubuntu 24.04.2 LTS (Noble Numbat) — Desktop',
    size: 5942960128,
    seeds: 1847,
    leechers: 234,
    source: 'ubuntu.com',
    category: 'linux',
    tags: ['ubuntu', 'gnome', 'desktop', 'lts', 'noble', 'numbat'],
    description: 'Ubuntu Desktop LTS release with GNOME desktop environment. Long-term support until 2029.',
    torrentUrl: 'https://releases.ubuntu.com/24.04/ubuntu-24.04.2-desktop-amd64.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://ubuntu.com/download/desktop',
  },
  {
    id: 'ubuntu-24.04.2-server',
    name: 'Ubuntu 24.04.2 LTS (Noble Numbat) — Server',
    size: 2748779069,
    seeds: 956,
    leechers: 89,
    source: 'ubuntu.com',
    category: 'linux',
    tags: ['ubuntu', 'server', 'lts', 'cloud'],
    description: 'Ubuntu Server LTS for cloud and server deployments.',
    torrentUrl: 'https://releases.ubuntu.com/24.04/ubuntu-24.04.2-live-server-amd64.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://ubuntu.com/download/server',
  },
  {
    id: 'fedora-41-workstation',
    name: 'Fedora 41 Workstation — Live ISO',
    size: 2254857830,
    seeds: 723,
    leechers: 112,
    source: 'fedoraproject.org',
    category: 'linux',
    tags: ['fedora', 'gnome', 'workstation', 'rpm', 'redhat'],
    description: 'Fedora Workstation with GNOME, cutting-edge packages and SELinux.',
    torrentUrl: 'https://torrent.fedoraproject.org/torrents/Fedora-Workstation-Live-x86_64-41.torrent',
    magnetLink: null,
    pageUrl: 'https://fedoraproject.org/workstation/download',
  },
  {
    id: 'debian-12.8-amd64',
    name: 'Debian 12.8 "Bookworm" — DVD ISO',
    size: 3984588800,
    seeds: 534,
    leechers: 67,
    source: 'debian.org',
    category: 'linux',
    tags: ['debian', 'bookworm', 'stable', 'dvd', 'universal'],
    description: 'Debian stable release, the universal operating system. Rock-solid stability.',
    torrentUrl: 'https://cdimage.debian.org/debian-cd/current/amd64/bt-dvd/debian-12.8.0-amd64-DVD-1.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://www.debian.org/CD/torrent-cd/',
  },
  {
    id: 'arch-linux-2025.01',
    name: 'Arch Linux 2025.01.01 — Installation Medium',
    size: 1106247680,
    seeds: 1203,
    leechers: 201,
    source: 'archlinux.org',
    category: 'linux',
    tags: ['arch', 'rolling', 'minimal', 'diy', 'btw'],
    description: 'Arch Linux rolling release. Lightweight, flexible, keep it simple.',
    torrentUrl: 'https://archlinux.org/releng/releases/2025.01.01/torrent/',
    magnetLink: 'magnet:?xt=urn:btih:ab6ad7ff24b5ed3a3f1d96f3b1c7a1f2d3e5c7f9&dn=archlinux-2025.01.01-x86_64.iso',
    pageUrl: 'https://archlinux.org/download/',
  },
  {
    id: 'linux-mint-22-cinnamon',
    name: 'Linux Mint 22 "Wilma" — Cinnamon Edition',
    size: 2952790016,
    seeds: 892,
    leechers: 145,
    source: 'linuxmint.com',
    category: 'linux',
    tags: ['mint', 'cinnamon', 'beginner', 'desktop'],
    description: 'Linux Mint with Cinnamon desktop. Elegant, easy to use, comfortable.',
    torrentUrl: 'https://torrents.linuxmint.com/torrents/linuxmint-22-cinnamon-64bit.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://linuxmint.com/download.php',
  },
  {
    id: 'manjaro-24-gnome',
    name: 'Manjaro 24.2 — GNOME Edition',
    size: 3865470566,
    seeds: 412,
    leechers: 78,
    source: 'manjaro.org',
    category: 'linux',
    tags: ['manjaro', 'gnome', 'arch', 'friendly', 'rolling'],
    description: 'Manjaro Linux with GNOME. User-friendly Arch-based distribution.',
    torrentUrl: 'https://download.manjaro.org/gnome/24.2/manjaro-gnome-24.2-241220-linux612.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://manjaro.org/download/',
  },
  {
    id: 'pop-os-22.04',
    name: 'Pop!_OS 22.04 LTS — NVIDIA Edition',
    size: 2936012800,
    seeds: 678,
    leechers: 89,
    source: 'pop.system76.com',
    category: 'linux',
    tags: ['pop', 'popos', 'system76', 'nvidia', 'gaming', 'cosmic'],
    description: 'Pop!_OS by System76. Optimized for creators and gamers with NVIDIA support.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:c4a23e8f1d96b3c7a1f2d3e5c7f9ab6ad7ff24b5&dn=pop-os_22.04_amd64_nvidia_42.iso',
    pageUrl: 'https://pop.system76.com/',
  },
  {
    id: 'kali-2024.4',
    name: 'Kali Linux 2024.4 — Live AMD64',
    size: 4194304000,
    seeds: 1567,
    leechers: 345,
    source: 'kali.org',
    category: 'linux',
    tags: ['kali', 'security', 'pentest', 'hacking', 'offensive'],
    description: 'Kali Linux for penetration testing and security auditing. 600+ tools.',
    torrentUrl: 'https://cdimage.kali.org/kali-2024.4/kali-linux-2024.4-live-amd64.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://www.kali.org/get-kali/',
  },
  {
    id: 'opensuse-leap-15.6',
    name: 'openSUSE Leap 15.6 — DVD ISO',
    size: 4294967296,
    seeds: 289,
    leechers: 45,
    source: 'opensuse.org',
    category: 'linux',
    tags: ['opensuse', 'suse', 'leap', 'enterprise', 'yast'],
    description: 'openSUSE Leap. Regular releases with enterprise-grade stability.',
    torrentUrl: 'https://download.opensuse.org/distribution/leap/15.6/iso/openSUSE-Leap-15.6-DVD-x86_64-Media.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://get.opensuse.org/leap/',
  },
  {
    id: 'elementary-os-8',
    name: 'elementary OS 8 — Desktop',
    size: 3006477107,
    seeds: 356,
    leechers: 56,
    source: 'elementary.io',
    category: 'linux',
    tags: ['elementary', 'pantheon', 'macos', 'beautiful', 'vala'],
    description: 'elementary OS. A fast, thoughtful, and capable replacement for Windows and macOS.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2d3e5&dn=elementaryos-8.0-stable.20250101.iso',
    pageUrl: 'https://elementary.io/',
  },
  {
    id: 'zorin-os-17',
    name: 'Zorin OS 17.2 Core — Desktop',
    size: 3489660928,
    seeds: 445,
    leechers: 67,
    source: 'zorin.com',
    category: 'linux',
    tags: ['zorin', 'windows', 'beginner', 'desktop', 'gnome'],
    description: 'Zorin OS. The alternative to Windows and macOS designed to make your computer faster.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2d3e5c7f9&dn=Zorin-OS-17.2-Core-64-bit.iso',
    pageUrl: 'https://zorin.com/os/download/',
  },
  // ── NEW: More distros ──
  {
    id: 'cachyos-desktop-2025.01',
    name: 'CachyOS Desktop 2025.01 — KDE Plasma',
    size: 2684354560,
    seeds: 312,
    leechers: 87,
    source: 'cachyos.org',
    category: 'linux',
    tags: ['cachyos', 'cachy', 'kde', 'plasma', 'performance', 'arch', 'gaming', 'optimized'],
    description: 'CachyOS — performance-optimized Arch-based distro with BORE scheduler, LLVM-optimized packages, and auto-GPU detection.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:a1f2d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7a1&dn=cachyos-desktop-2025.01-x86_64.iso',
    pageUrl: 'https://cachyos.org/download/',
  },
  {
    id: 'endeavouros-galileo',
    name: 'EndeavourOS Galileo Neo — Live ISO',
    size: 1932735283,
    seeds: 478,
    leechers: 92,
    source: 'endeavouros.com',
    category: 'linux',
    tags: ['endeavouros', 'endeavour', 'arch', 'installer', 'calamares'],
    description: 'EndeavourOS — a terminal-centric Arch-based distro that makes Arch accessible to everyone.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:b3c7a1f2d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3&dn=EndeavourOS_Galileo-Neo-2024.09.22.iso',
    pageUrl: 'https://endeavouros.com/latest-release/',
  },
  {
    id: 'nixos-24.11',
    name: 'NixOS 24.11 "Vicuña" — Graphical ISO',
    size: 2684354560,
    seeds: 567,
    leechers: 78,
    source: 'nixos.org',
    category: 'linux',
    tags: ['nixos', 'nix', 'functional', 'declarative', 'reproducible'],
    description: 'NixOS — the purely functional Linux distribution. Declarative config, atomic upgrades, rollbacks.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2d3&dn=nixos-graphical-24.11.1-x86_64-linux.iso',
    pageUrl: 'https://nixos.org/download/',
  },
  {
    id: 'void-linux-glibc',
    name: 'Void Linux — Live x86_64 (glibc)',
    size: 734003200,
    seeds: 234,
    leechers: 34,
    source: 'voidlinux.org',
    category: 'linux',
    tags: ['void', 'runit', 'independent', 'rolling', 'xbps'],
    description: 'Void Linux — independent distro with runit init system and XBPS package manager.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2d5e7&dn=void-live-x86_64-20240314-base.iso',
    pageUrl: 'https://voidlinux.org/download/',
  },
  {
    id: 'gentoo-install-2025',
    name: 'Gentoo Linux — Install AMD64 Minimal',
    size: 524288000,
    seeds: 189,
    leechers: 23,
    source: 'gentoo.org',
    category: 'linux',
    tags: ['gentoo', 'compile', 'portage', 'source', 'performance'],
    description: 'Gentoo Linux — compile everything from source for maximum performance and customization.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2d3e5c8a2&dn=install-amd64-minimal-20250101.iso',
    pageUrl: 'https://www.gentoo.org/downloads/',
  },
  {
    id: 'opensuse-tumbleweed',
    name: 'openSUSE Tumbleweed — DVD Snapshot',
    size: 4831838208,
    seeds: 367,
    leechers: 56,
    source: 'opensuse.org',
    category: 'linux',
    tags: ['opensuse', 'tumbleweed', 'rolling', 'kde', 'tested'],
    description: 'openSUSE Tumbleweed — rolling release with automated testing via openQA.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:c7a1f2d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3c8&dn=openSUSE-Tumbleweed-DVD-x86_64-Snapshot.iso',
    pageUrl: 'https://get.opensuse.org/tumbleweed/',
  },
  {
    id: 'mx-linux-23.4',
    name: 'MX Linux 23.4 "Libretto" — KDE Plasma',
    size: 2415919104,
    seeds: 523,
    leechers: 78,
    source: 'mxlinux.org',
    category: 'linux',
    tags: ['mx', 'mxlinux', 'debian', 'antiX', 'fast', 'stable'],
    description: 'MX Linux — midweight distro based on Debian stable. Fast, reliable, and full-featured.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:a1f2d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7b2&dn=MX-23.4_KDE_x64.iso',
    pageUrl: 'https://mxlinux.org/download-links/',
  },
  {
    id: 'garuda-linux-dragonized',
    name: 'Garuda Linux Dragonized — KDE dr460nized',
    size: 3489660928,
    seeds: 345,
    leechers: 67,
    source: 'garudalinux.org',
    category: 'linux',
    tags: ['garuda', 'dragonized', 'arch', 'kde', 'gaming', 'btrfs'],
    description: 'Garuda Linux — performance-focused Arch-based distro with BTRFS snapshots and a stunning KDE theme.',
    torrentUrl: null,
    magnetLink: 'magnet:?xt=urn:btih:d3e5c7f9ab6ad7ff24b5ed3a3f1d96b3c7a1f2c4&dn=garuda-dr460nized-linux-zen-250101.iso',
    pageUrl: 'https://garudalinux.org/downloads',
  },
  {
    id: 'ubuntu-kubuntu-24.04',
    name: 'Kubuntu 24.04.2 LTS — KDE Plasma Desktop',
    size: 4194304000,
    seeds: 456,
    leechers: 67,
    source: 'kubuntu.org',
    category: 'linux',
    tags: ['kubuntu', 'kde', 'plasma', 'ubuntu', 'desktop'],
    description: 'Kubuntu — Ubuntu with the KDE Plasma desktop. Beautiful, customizable, and powerful.',
    torrentUrl: 'https://cdimage.ubuntu.com/kubuntu/releases/24.04/release/kubuntu-24.04.2-desktop-amd64.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://kubuntu.org/getkubuntu/',
  },
  {
    id: 'tails-6.10',
    name: 'Tails 6.10 — Portable Privacy OS',
    size: 1395864371,
    seeds: 678,
    leechers: 123,
    source: 'tails.net',
    category: 'linux',
    tags: ['tails', 'tor', 'privacy', 'anonymous', 'live', 'amnesic'],
    description: 'Tails — portable OS that protects against surveillance. Routes all traffic through Tor.',
    torrentUrl: 'https://tails.net/torrents/files/tails-amd64-6.10.torrent',
    magnetLink: null,
    pageUrl: 'https://tails.net/install/',
  },
  {
    id: 'qubes-os-4.2',
    name: 'Qubes OS 4.2.4 — Security-focused Desktop',
    size: 6442450944,
    seeds: 234,
    leechers: 45,
    source: 'qubes-os.org',
    category: 'linux',
    tags: ['qubes', 'security', 'xen', 'compartmentalization', 'privacy'],
    description: 'Qubes OS — reasonably secure OS using Xen-based virtualization for compartmentalization.',
    torrentUrl: 'https://ftp.qubes-os.org/iso/Qubes-R4.2.4-x86_64.iso.torrent',
    magnetLink: null,
    pageUrl: 'https://www.qubes-os.org/downloads/',
  },
];

/**
 * Search Linux ISOs with word-level matching for better results
 */
export function searchLinuxISOs(query) {
  const q = query.toLowerCase().trim();
  if (!q) return LINUX_ISOS;

  const words = q.split(/\s+/).filter(Boolean);

  return LINUX_ISOS.filter((iso) => {
    const searchText = [
      iso.name,
      iso.description,
      iso.source,
      ...(iso.tags || []),
    ].join(' ').toLowerCase();

    // All words must match somewhere in the search text
    return words.every(word => searchText.includes(word));
  }).sort((a, b) => {
    // Prioritize exact name matches
    const aNameMatch = a.name.toLowerCase().includes(q);
    const bNameMatch = b.name.toLowerCase().includes(q);
    if (aNameMatch && !bNameMatch) return -1;
    if (!aNameMatch && bNameMatch) return 1;

    // Then by tag matches
    const aTagMatch = (a.tags || []).some(t => t.includes(q));
    const bTagMatch = (b.tags || []).some(t => t.includes(q));
    if (aTagMatch && !bTagMatch) return -1;
    if (!aTagMatch && bTagMatch) return 1;

    return (b.seeds || 0) - (a.seeds || 0);
  });
}

export function getAllLinuxISOs() {
  return LINUX_ISOS;
}
